site_name: FakeSite
site_url: https://spisakt.github.io/fakesite
nav:
    - Home: index.md
    - Version 2.x:
        - Songs: 
            - Mistyness: docs/songs/mistyness.md

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
