nav:
- Home: index.md
- Songs:
  - Just Friends: songs/justfriends.md
  - Another You: songs/anotheryou.md
  - Misty: songs/misty.md
  - Someday my prince will come: songs/someday.md
site_name: FakeSite
site_url: https://spisakt.github.io/fakesite
theme:
  custom_dir: custom_theme/
  name: slate
