nav:
- Home: index.md
- Songs:
  - Trouble in mind: songs/troubleinmind.md
  - Body and Soul: songs/bodyandsoul.md
  - Beautiful Love: songs/beautifulllove.md
  - Another You: songs/anotheryou.md
  - Misty: songs/misty.md
  - Just Friends: songs/justfriends.md
  - Someday my prince will come: songs/someday.md
site_name: FakeSite
site_url: https://spisakt.github.io/fakesite
theme:
  custom_dir: custom_theme/
  name: slate
